import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={cn(inter.className, "min-h-dvh")}>
        <header className="container h-16 bg-red-300 border-b flex items-center justify-between">
          <h2>test</h2>
          <ul className="flex items-center gap-4">
            <li>Home</li>
            <li>About</li>
            <li>about</li>
          </ul>
        </header>
        {children}
        <footer className="container h-16 bg-red-500 border-t flex items-center top-full sticky">
          <div>&copy;y</div>
        </footer>
      </body>
    </html>
  );
}
